@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

ResumeBook *-right-> "5" UniqueItemList
ResumeBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueItemList
UniqueTagList -[hidden]down- UniqueItemList

UniqueTagList *-right-> "*" Tag
UniqueItemList o-right-> "*"Item

Item o-up-> "*" Tag

Item *--> "1" Name
Item *--> "1" Type
Item *--> "*" Time
Item *--> "*" Description

@enduml
