@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ResumeBookParser" as ResumeBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteResumeCommand" as DeleteResumeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1 i/res")
activate LogicManager

LogicManager -> ResumeBookParser : parseCommand("delete 1 i/ res")
activate ResumeBookParser

create DeleteCommandParser
ResumeBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> ResumeBookParser
deactivate DeleteCommandParser

ResumeBookParser -> DeleteCommandParser : parse("1 i/ res")
activate DeleteCommandParser

create DeleteResumeCommand
DeleteCommandParser -> DeleteResumeCommand
activate DeleteResumeCommand

DeleteResumeCommand --> DeleteCommandParser : d
deactivate DeleteResumeCommand

DeleteCommandParser --> ResumeBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> ResumeBookParser
destroy DeleteCommandParser

ResumeBookParser --> LogicManager : d
deactivate ResumeBookParser

LogicManager -> DeleteResumeCommand : execute()
activate DeleteResumeCommand

DeleteResumeCommand -> Model : deleteResume(1)
activate Model

Model --> DeleteResumeCommand
deactivate Model

create CommandResult
DeleteResumeCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteResumeCommand
deactivate CommandResult

DeleteResumeCommand --> LogicManager : result
deactivate DeleteResumeCommand

[<--LogicManager
deactivate LogicManager
@enduml
