@startuml
start
:user executes EditNoteCommand;

if () then ([invalid indices are present])
    :throw invalid index exception;
else ([else])
    :get note to edit from model
    based on index;
    :create edited note from
    descriptor;
    if () then ([note present in model])
        :throw duplicate note exception;
    else ([else])
        :update note to edited version in model;
        :commit resume book;
        :display edited note in note list;
    endif
    :show updated note message to user;
    :show updated note detail to user;
endif
stop
@enduml