@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Interface ReadOnlyResumeBook <<Interface>>
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class ResumeBook
Class ReadOnlyResumeBook
Class UniqueItemList

Package User {
Class Person
Package UserField {
Class Phone
Class Email
Class Github
Class University
}
}

Package Item {
Class Item
Class Resume
Class Internship
Class Project
Class Skill

Package ItemField {
Class Type
Class Description
Class Website
Class Level
Class Tag
}
}

Package SharedField {
Class Name
Class Time
}

Class HiddenOutside #FFFFFF
HiddenOutside .d.> Model
Model .u.> ObservableList
ModelManager .u.> Model

ModelManager o-l-> "1" UserPrefs
UserPrefs .l.|> ReadOnlyUserPrefs

ModelManager o-r-> "1" ResumeBook
ResumeBook .u.|> ReadOnlyResumeBook

ResumeBook *-d-> "1" Person
Person *---> "1" Name
Person *---> "2" Time
Person *---> "1" Phone
Person *---> "1" Email
Person *---> "1" Github
Person *---> "1" University

ResumeBook *--> "4" UniqueItemList
UniqueItemList o--> "*" Item

Item *---> "1" Name
Item *---> "*" Time
Item *---> "1" Type
Item *---> "1" Description
Item *---> "*" Tag

Project ..|> Item
Skill ..|> Item
Resume ..|> Item
Internship ..|> Item

Project *-> "1" Website
Skill *-> "1" Level

}
@enduml
