@startuml
!include style.puml
skinparam arrowThickness 1.5
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface ResumeBookStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonResumeBookStorage

StorageManager .up.|> Storage
StorageManager o-left-> UserPrefsStorage
StorageManager o-> ResumeBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonResumeBookStorage .up.|> ResumeBookStorage
JsonResumeBookStorage .down.> JsonSerializableResumeBook

JsonSerializableResumeBook o-right- "1" JsonAdaptedPerson
JsonSerializableResumeBook o-down- "*" JsonAdaptedInternship
JsonSerializableResumeBook o-down- "*" JsonAdaptedProject
JsonSerializableResumeBook o-down- "*" JsonAdaptedResume
JsonSerializableResumeBook o-down- "*" JsonAdaptedSkill
JsonSerializableResumeBook o-down- "*" JsonAdaptedNote

JsonAdaptedInternship *-down- "*" JsonAdaptedTag
JsonAdaptedProject *-down- "*" JsonAdaptedTag
JsonAdaptedResume *-down- "*" JsonAdaptedTag
JsonAdaptedSkill *-down- "*" JsonAdaptedTag
JsonAdaptedNote *-down- "*" JsonAdaptedTag
hide field
@enduml

