@startuml
!include style.puml
skinparam arrowThickness 1.5
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface ResumeBookStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonResumeBookStorage

StorageManager .up.|> Storage
StorageManager o-left-> UserPrefsStorage
StorageManager o-> ResumeBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonResumeBookStorage .up.|> ResumeBookStorage
JsonResumeBookStorage .down.> JsonSerializableResumeBook

JsonSerializableResumeBook .right.> JsonAdaptedPerson
JsonSerializableResumeBook .down.> JsonAdaptedInternship
JsonSerializableResumeBook .down.> JsonAdaptedProject
JsonSerializableResumeBook .down.> JsonAdaptedResume
JsonSerializableResumeBook .down.> JsonAdaptedSkill
JsonSerializableResumeBook .down.> JsonAdaptedNote

JsonAdaptedInternship .down.> JsonAdaptedTag
JsonAdaptedProject .down.> JsonAdaptedTag
JsonAdaptedResume .down.> JsonAdaptedTag
JsonAdaptedSkill .down.> JsonAdaptedTag
JsonAdaptedNote .down.> JsonAdaptedTag

@enduml

