@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR
skinparam classBackgroundColor UI_COLOR
skinparam defaultFontSize 15
skinparam nodesep 90
skinparam ranksep 130

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "            {abstract}            \n            UiPart            " as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class ItemDisplayList
Class ItemCard
Class ItemListPanel
Class UserDetailPane
Class UserOverallPane
Class UserProfilePane
Class NoteListPanel
Class NoteCard
Class StatusBarFooter
Class CommandBox
Class PreviewWindow

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager ..|> Ui
UiManager --> MainWindow

MainWindow *---> HelpWindow
MainWindow *---> CommandBox

MainWindow *---> ResultDisplay
MainWindow *---> StatusBarFooter
MainWindow *---> PreviewWindow
MainWindow *---> ItemDisplayList

MainWindow *---> ItemListPanel
MainWindow *---> UserOverallPane
MainWindow *---> NoteListPanel

ItemListPanel --> ItemCard
NoteListPanel --> NoteCard
UserOverallPane *->UserProfilePane
UserOverallPane *->UserDetailPane

MainWindow ---|> UiPart
ItemDisplayList ---|> UiPart
ResultDisplay ---|> UiPart
CommandBox ---|> UiPart
PreviewWindow ---|> UiPart
ItemCard --|> UiPart
NoteCard --|> UiPart
StatusBarFooter ---|> UiPart
UserDetailPane -left-|> UiPart
UserProfilePane -left-|> UiPart
HelpWindow ---|> UiPart
UserOverallPane ---|> UiPart
ItemListPanel ---|> UiPart
NoteListPanel ---|> UiPart

UiManager -u-> Logic
MainWindow -u-> Logic
ItemCard ...> Model
NoteCard ...> Model
UserOverallPane ...> Model

HelpWindow -[hidden]right- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

NoteListPanel -[hidden]left- PreviewWindow
NoteListPanel -[hidden]left- UserOverallPane


MainWindow -[hidden]-|> UiPart

}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}
@enduml
