@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ResumeBookParser" as ResumeBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedResumeBook" as VersionedResumeBook MODEL_COLOR
end box
[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> ResumeBookParser : parseCommand("undo")
activate ResumeBookParser

create UndoCommand
ResumeBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> ResumeBookParser
deactivate UndoCommand

ResumeBookParser --> LogicManager : u
deactivate ResumeBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoResumeBook()
activate Model

Model -> VersionedResumeBook : undo()
activate VersionedResumeBook

VersionedResumeBook -> VersionedResumeBook :resetData(ReadOnlyResumeBook)
VersionedResumeBook -> VersionedResumeBook :setItemsToDisplay(String)
VersionedResumeBook --> Model :
deactivate VersionedResumeBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
