= Pham Thuy Duong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:icons: font

== PROJECT: ResuMe

== Overview

*ResuMe* is a desktop application for you to manage all of your resumes from a centralised location.
It is easy to build, customise and export different resume versions using only *Command Line Interface*.

Our developer team consists of five Year 2 Computer Science students from the National University of Singapore.
This six-week project is a component of our CS2103T Software Engineering module, and is built upon the code from
https://github.com/nus-cs2103-AY1920S2/addressbook-level3[AddressBook Level 3].

== Summary of Contributions

=== 1. Individual Contributions

==== 1.1. Contributions to Source Code

You can view my code contributions via https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=duongphammmm&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=duongphammmm&tabRepo=AY1920S2-CS2103T-F10-1%2Fmain%5Bmaster%5D[RepoSense]

* *Major enhancement*: added the ability to generate a `.pdf` file from an existing resume
** What it does: allows users to export their resume to a well-formatted and printable `.pdf` version, which could be
directly submitted to their potential employer.
** Justification: This feature improves the product significantly because users do not need to spend time on manually
formatting the final product, making it much more efficient and convenient to create new usable resume using the application.
** Highlights: This enhancement involves an external library that supports building a `.pdf` file  using Java. It was
challenging as it requires a steep learning curve in order to integrate the library into our application, while keeping
in mind of both our design consideration and existing architecture.
** Credits: `Apache Pdf Box` (https://github.com/AY1920S2-CS2103T-F10-1/main/pull/142[#142])

* *Minor enhancement*: added more depth to `help` command, where user can either view a `Command Summary` for all available
commands, or a `Getting Started` guideline. Both command options will open a new pop-up window to maximise readability
and facilitate easy cross-reference.

* *Minor enhancement*: integrated the `add` command with our new `model` implementation to support more item type like
`internship`, `project` and `skill`. Each item type has their own set of attributes, and hence needs a separate
 `command` and `parser` class for the `add` function.

==== 1.2. Contributions to Documentation:
** Updated README (https://github.com/AY1920S2-CS2103T-F10-1/main/pull/161[#161])
** Updated the <<Contributions to the User Guide (Extracts), User Guide>> for the following sections: About this guide,
Viewing help: `help`, Adding an item: `add`, Generating a resume: `rgen`

** Updated the <<Contributions to the Developer Guide (Extracts), Developer Guide>> for the following sections: Model Component,
Export Feature, Appendix A: Product Scope, Appendix D: Non Functional Requirements, Appendix E: Glossary

=== 2. Team Contributions
==== 2.1. Model Refactoring
** What it means: `Item` is now an _abstract_ class with five different subclasses: `Internship`, `Project`, `Skill`, `Resume` and `Note`.
Each type of item also has its own set of attributes, utilising field classes like `Name`, `Time`, `Role`, `Website`, `Level`, `Description`, ect...
** Justification: This ensures flexibility for the user to customise their experiences according their the nature.
With such variety of attributes, implementing each type as a separate class is more in line with OOP principles.
** Refactoring Pull Requests: https://github.com/AY1920S2-CS2103T-F10-1/main/pull/66[#66],
https://github.com/AY1920S2-CS2103T-F10-1/main/pull/73[#73],
https://github.com/AY1920S2-CS2103T-F10-1/main/pull/75[#75],...

==== 2.2. Testing
Test Pull Requests: https://github.com/AY1920S2-CS2103T-F10-1/main/pull/136[#136],
https://github.com/AY1920S2-CS2103T-F10-1/main/pull/187[#187],
https://github.com/AY1920S2-CS2103T-F10-1/main/pull/236[#236],
https://github.com/AY1920S2-CS2103T-F10-1/main/pull/253[#253],
https://github.com/AY1920S2-CS2103T-F10-1/main/pull/254[#254],...

==== 2.3. Reviewing:
*** Reviewed Pull Requests with non-trivial review comments: https://github.com/AY1920S2-CS2103T-F10-1/main/pull/159[#159],
https://github.com/AY1920S2-CS2103T-F10-1/main/pull/25[#25],
https://github.com/AY1920S2-CS2103T-F10-1/main/pull/86[#86],
https://github.com/AY1920S2-CS2103T-F10-1/main/pull/256[#256],...
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/duongphammmm/ped/issues/2[1],
https://github.com/duongphammmm/ped/issues/7[2], https://github.com/duongphammmm/ped/issues/9[3])

== Contributions to the User Guide (Extracts)
|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===
include::../UserGuide.adoc[tag=guide]

include::../UserGuide.adoc[tag=add]

include::../UserGuide.adoc[tag=rgen]

== Contributions to the Developer Guide (Extracts)

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=model]

include::../DeveloperGuide.adoc[tag=export]

